"""init_procurement_and_settings

Revision ID: 76c7ea70261e
Revises: 
Create Date: 2026-09-29 12:35:41.349895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c7ea70261e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pic_id', sa.String(), nullable=False),
    sa.Column('pic_name', sa.String(), nullable=False),
    sa.Column('fpp_id', sa.String(), nullable=False),
    sa.Column('fpp_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('operational_status', sa.String(), nullable=False),
    sa.Column('operational_status_reason', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('stage_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_requests_id'), 'procurement_requests', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_notifications', sa.Boolean(), nullable=True),
    sa.Column('sla_warning_days', sa.Integer(), nullable=True),
    sa.Column('auto_escalation', sa.Boolean(), nullable=True),
    sa.Column('auto_escalate_days', sa.Integer(), nullable=True),
    sa.Column('escalation_manager_id', sa.String(), nullable=True),
    sa.Column('approval_threshold', sa.Float(), nullable=True),
    sa.Column('department_reviewers', sa.JSON(), nullable=True),
    sa.Column('milestone_durations', sa.JSON(), nullable=True),
    sa.Column('ai_sensitivity', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_milestones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pic_id', sa.String(), nullable=True),
    sa.Column('pic_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_milestones_id'), 'procurement_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_milestones_request_id'), 'procurement_milestones', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_milestones_request_id'), table_name='procurement_milestones')
    op.drop_index(op.f('ix_procurement_milestones_id'), table_name='procurement_milestones')
    op.drop_table('procurement_milestones')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_procurement_requests_id'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    # ### end Alembic commands ###
