"""Add Guarantee Model

Revision ID: b7d8c9f0e1a2
Revises: 76c7ea70261e
Create Date: 2026-10-07 16:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d8c9f0e1a2'
down_revision: Union[str, None] = '76c7ea70261e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guarantees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('reference_no', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('issuer_type', sa.String(), nullable=True),
    sa.Column('beneficiary', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pic_id', sa.String(), nullable=False),
    sa.Column('pic_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('next_action', sa.String(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guarantees_id'), 'guarantees', ['id'], unique=False)
    op.create_index(op.f('ix_guarantees_reference_no'), 'guarantees', ['reference_no'], unique=False)
    op.create_index(op.f('ix_guarantees_request_id'), 'guarantees', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guarantees_request_id'), table_name='guarantees')
    op.drop_index(op.f('ix_guarantees_reference_no'), table_name='guarantees')
    op.drop_index(op.f('ix_guarantees_id'), table_name='guarantees')
    op.drop_table('guarantees')
    # ### end Alembic commands ###
