"""init_deadlines

Revision ID: 2748aabb97b7
Revises: b7d8c9f0e1a2
Create Date: 2026-10-08 08:56:23.047611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2748aabb97b7'
down_revision: Union[str, None] = 'b7d8c9f0e1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('milestone', sa.String(length=100), nullable=False),
    sa.Column('pic_id', sa.String(length=50), nullable=False),
    sa.Column('pic_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('urgency_level', sa.String(length=50), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('overdue_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_id'), 'deadlines', ['id'], unique=False)
    op.create_index(op.f('ix_deadlines_request_id'), 'deadlines', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deadlines_request_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_id'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
