"""
Abstract repository interfaces for domain layer.
Concrete implementations live in src/infrastructure/repositories/
"""
from abc import ABC, abstractmethod
from typing import List, Optional
from src.domain.entities.procurement import ProcurementRequest, ProcurementMilestone
from src.domain.entities.document import DocumentItem
from src.domain.entities.guarantee import GuaranteeItem
from src.domain.entities.deadline import DeadlineItem
from src.domain.entities.user import User


class ProcurementRepository(ABC):
    @abstractmethod
    async def get_all(self) -> List[ProcurementRequest]: ...
    @abstractmethod
    async def get_by_id(self, id: str) -> Optional[ProcurementRequest]: ...
    @abstractmethod
    async def create(self, request: ProcurementRequest) -> ProcurementRequest: ...
    @abstractmethod
    async def update(self, id: str, request: ProcurementRequest) -> ProcurementRequest: ...
    @abstractmethod
    async def delete(self, id: str) -> None: ...


class DocumentRepository(ABC):
    @abstractmethod
    async def get_by_request(self, request_id: str) -> List[DocumentItem]: ...
    @abstractmethod
    async def get_by_id(self, id: str) -> Optional[DocumentItem]: ...
    @abstractmethod
    async def create(self, document: DocumentItem) -> DocumentItem: ...
    @abstractmethod
    async def update_status(self, id: str, status: str) -> DocumentItem: ...


class GuaranteeRepository(ABC):
    @abstractmethod
    async def get_by_request(self, request_id: str) -> List[GuaranteeItem]: ...
    @abstractmethod
    async def get_by_id(self, id: str) -> Optional[GuaranteeItem]: ...
    @abstractmethod
    async def create(self, guarantee: GuaranteeItem) -> GuaranteeItem: ...
    @abstractmethod
    async def update(self, id: str, guarantee: GuaranteeItem) -> GuaranteeItem: ...


class DeadlineRepository(ABC):
    @abstractmethod
    async def get_by_request(self, request_id: str) -> List[DeadlineItem]: ...
    @abstractmethod
    async def get_all_active(self) -> List[DeadlineItem]: ...
    @abstractmethod
    async def get_by_id(self, id: str) -> Optional[DeadlineItem]: ...
    @abstractmethod
    async def create(self, deadline: DeadlineItem) -> DeadlineItem: ...
    @abstractmethod
    async def update(self, id: str, deadline: DeadlineItem) -> DeadlineItem: ...


class UserRepository(ABC):
    @abstractmethod
    async def get_all(self) -> List[User]: ...
    @abstractmethod
    async def get_by_id(self, id: str) -> Optional[User]: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[User]: ...
    @abstractmethod
    async def create(self, user: User) -> User: ...
    @abstractmethod
    async def update(self, id: str, user: User) -> User: ...
